=== atomless/akdv-rnd/mpulse-dswb-widgets/src/data/datajots/stages.schema.json
{
  "definitions": {}, 
  "$schema": "http://json-schema.org/draft-06/schema#", 
  "$id": "http://example.com/example.json", 
  "type": "object", 
  "additionalProperties": true, 
  "properties": {
    "name": {
      "type": "string", 
      "title": "The Name Schema.", 
      "description": "An explanation about the purpose of this instance.", 
      "default": "", 
      "examples": [
        "Demo Session Data"
      ]
    }, 
    "description": {
      "type": "string", 
      "title": "The Description Schema.", 
      "description": "An explanation about the purpose of this instance.", 
      "default": "", 
      "examples": [
        "Session data over one day for an ecommerce client"
      ]
    }, 
    "theme": {
      "type": "string", 
      "title": "The Theme Schema.", 
      "description": "An explanation about the purpose of this instance.", 
      "default": "", 
      "examples": [
        "default"
      ]
    }, 
    "data_format": {
      "type": "string", 
      "title": "The Data_fomat Schema.", 
      "description": "An explanation about the purpose of this instance.", 
      "default": "", 
      "examples": [
        "tsv"
      ]
    }, 
    "stages": {
      "type": "array", 
      "additionalItems": true, 
      "uniqueItems": true, 
      "items": {
        "type": "object", 
        "additionalProperties": true, 
        "properties": {
          "id": {
            "type": "integer", 
            "title": "The Id Schema.", 
            "description": "An explanation about the purpose of this instance.", 
            "default": 0, 
            "examples": [
              1
            ]
          }, 
          "anchortext": {
            "type": "string", 
            "title": "The Anchortext Schema.", 
            "description": "An explanation about the purpose of this instance.", 
            "default": "", 
            "examples": [
              "start"
            ]
          }, 
          "description": {
            "type": "string", 
            "title": "The Description Schema.", 
            "description": "An explanation about the purpose of this instance.", 
            "default": "", 
            "examples": [
              "shows all available data in a cloud"
            ]
          }, 
          "displaytext": {
            "type": "string", 
            "title": "The Displaytext Schema.", 
            "description": "An explanation about the purpose of this instance.", 
            "default": "", 
            "examples": [
              "{{count(*)}} sessions detected on {{appname}} on the day of {{date}}."
            ]
          }, 
          "dimensions": {
            "type": "array", 
            "additionalItems": true, 
            "uniqueItems": true, 
            "items": {
              "$id": "syrianbear", 
              "title": "Empty Object", 
              "description": "This accepts anything, as long as it's valid JSON."
            }
          }
        }, 
        "required": [
          "id", 
          "anchortext", 
          "description", 
          "displaytext", 
          "dimensions"
        ]
      }
    }
  }, 
  "required": [
    "name", 
    "description", 
    "theme", 
    "data_format", 
    "stages"
  ]
}

=== atomless/akdv-rnd/mpulse-dswb-widgets/src/data/datajots/trump/stages.json
{
    "name": "Cancer rates & survival",
    "description": "5 year survival rates from 2010 - 2015",
    "theme": "default",
    "data_format": "tsv",
    "stages": [
        {
            "id": 1,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "This cluster represents all tweets by @realDonaldTrump in 2017",
            "disableclustering": true,
            "dimensions": []
        },
        {
            "id": 2,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "Distributed by time on the x-axis",
            "dimensions": [
                {
                    "name": "x",
                    "properties": {
                        "by": "created_at"
                    }
                }
            ]
        },
        {
            "id": 3,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "Distributed by tweet length on the y-axis",
            "dimensions": [
                {
                    "name": "x",
                    "properties": {
                        "by": "created_at"
                    }
                },
                {
                    "name": "y",
                    "properties": {
                        "by": "length",
                        "reverse": true
                    }
                }
            ]
        },
        {
            "id": 4,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "Sized by favorite count",
            "dimensions": [
                {
                    "name": "x",
                    "properties": {
                        "by": "created_at"
                    }
                },
                {
                    "name": "y",
                    "properties": {
                        "by": "length"
                    }
                },
                {
                    "name": "radius",
                    "properties": {
                        "by": "favourite_count"
                    }
                }
            ]
        },
        {
            "id": 5,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "Colored by RTs",
            "dimensions": [
                {
                    "name": "x",
                    "properties": {
                        "by": "created_at"
                    }
                },
                {
                    "name": "y",
                    "properties": {
                        "by": "length"
                    }
                },
                {
                    "name": "color",
                    "properties": {
                        "by": "retweet_count",
                        "palette": ["hsl(240,100%,60%)", "hsl(120,100%,40%)"]
                    }
                },
                {
                    "name": "radius",
                    "properties": {
                        "by": "favourite_count"
                    }
                }
            ]
        }
    ]
}

=== atomless/akdv-rnd/mpulse-dswb-widgets/src/data/datajots/cancer/stages.json
{
    "name": "Cancer rates & survival",
    "description": "5 year survival rates from 2010 - 2015",
    "theme": "default",
    "data_format": "tsv",
    "stages": [
        {
            "id": 1,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "This cluster represents all cancer types we have data for in the UK",
            "dimensions": []
        },
        {
            "id": 2,
            "anchortext": "devicetypes",
            "description": "cluster all forms by type",
            "displaytext": "Sized by incidence",
            "dimensions": [
                {
                    "name": "radius",
                    "properties": {
                        "by": "number"
                    }
                }
            ]
        },
        {
            "id": 3,
            "anchortext": "devicetypes",
            "description": "cluster all sessions by device type name",
            "displaytext": "Sized by incidence, x axis by 5 year survival rate",
            "dimensions": [
                {
                    "name": "x",
                    "properties": {
                        "by": "survival"
                    }
                },
                {
                    "name": "radius",
                    "properties": {
                        "by": "number"
                    }
                }
            ]
        },
        {
            "id": 4,
            "anchortext": "devicetypes",
            "description": "cluster all sessions by device type name",
            "displaytext": "Sized by incidence, x axis by 5 year survival rate, coloured by gender",
            "dimensions": [
                {
                    "name": "radius",
                    "properties": {
                        "by": "number"
                    }
                },
                {
                    "name": "x",
                    "properties": {
                        "by": "survival"
                    }
                },
                {
                    "name": "color",
                    "properties": {
                        "by": "sex",
                        "palette": ["hsl(240,100%,50%)", "hsl(0,100%,50%)"]
                    }
                }
            ]
        }
    ]
}

=== atomless/akdv-rnd/mpulse-dswb-widgets/src/data/datajots/grainger/stages.json
{
    "name": "Demo Session Data",
    "description": "Session data over one day for an ecommerce client",
    "theme": "default",
    "data_format": "tsv",
    "stages": [
        {
            "id": 1,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "This cluster represents 5,000 sessions on Grainger.com on Thu Nov 23.",
            "dimensions": [
            ]
        },
        {
            "id": 2,
            "anchortext": "alloptions",
            "description": "shows all available options",
            "displaytext": "By COUNTRYCODE",
            "filters": [
                {
                    "DEVICETYPENAME": "desktop"
                }
            ],
            "dimensions": [
                { 
                    "name": "axis_y",
                    "properties" : {
                        "by": "COUNTRYCODE",
                        "label": "Country Code"
                    }
                },
                { 
                    "name": "color",
                    "properties" : {
                        "by": "DEVICETYPENAME",
                        "palette": ["hsl(220,100%,50%)", "hsl(190,100%,50%)", "hsl(120,100%,50%)", "hsl(80,100%,50%)", "hsl(40,100%,50%)", "hsl(350,100%,50%)"]
                    }
                },
                { 
                    "name": "opacity",
                    "properties" : {
                        "by": "SESSIONDURATION",
                        "reverse": false
                    }
                }
            ]
        },
        {
            "id": 3,
            "anchortext": "devicetypes",
            "description": "cluster all sessions by device type name",
            "displaytext": "87% of sessions were on Desktop<br/>10% of sessions were on Smartphone<br/>3% were on Tablet.",
            "dimensions": [
                {
                    "name": "x",
                    "properties": {
                        "by": "DEVICETYPENAME"
                    }
                },
                { 
                    "name": "color",
                    "properties" : {
                        "by": "DEVICETYPENAME",
                        "palette": ["hsl(220,100%,50%)", "hsl(190,100%,50%)", "hsl(120,100%,50%)", "hsl(80,100%,50%)", "hsl(40,100%,50%)", "hsl(350,100%,50%)"]
                    }
                }
            ]
        },
        {
            "id": 4,
            "anchortext": "countries",
            "description": "cluster all sessions by countries",
            "displaytext": "97% of sessions were from The United States.",
            "dimensions": [
                {
                    "name": "x",
                    "properties": {
                        "by": "COUNTRYCODE",
                         "palette": ["hsl(220,100%,50%)", "hsl(190,100%,50%)", "hsl(120,100%,50%)", "hsl(80,100%,50%)", "hsl(40,100%,50%)", "hsl(350,100%,50%)"]
                    }
                },
                {
                    "name": "x",
                    "properties": {
                        "by": "COUNTRYCODE"
                    }
                },
                {
                    "name": "color",
                    "properties": {
                        "by": "COUNTRYCODE",
                        "palette": ["hsl(220,100%,50%)", "hsl(190,100%,50%)", "hsl(120,100%,50%)", "hsl(80,100%,50%)", "hsl(40,100%,50%)", "hsl(350,100%,50%)"]
                    }
                }
            ]
        },
        {
            "id": 5,
            "anchortext": "countries",
            "description": "vertical distribution of performance, with #1 country highlighted",
            "displaytext": "Sessions from The United States averaged 3.9 seconds",
            "dimensions": [
                {   
                    "name": "color",
                    "properties": {
                        "by": "COUNTRYCODE",
                        "palette": ["hsl(220,100%,50%)", "hsl(190,100%,50%)", "hsl(120,100%,50%)", "hsl(80,100%,50%)", "hsl(40,100%,50%)", "hsl(350,100%,50%)"]
                    }
                },
                {
                    "name": "y",
                    "properties": {
                        "by": "PAGELOADTIME"
                    }
                }
            ]
        },
        {
            "id": 6,
            "anchortext": "conversion",
            "description": "sessions highlighted by conversion",
            "displaytext": "2.9% of sessions converted",
            "dimensions": [
                {   
                    "name": "color",
                    "properties": {
                        "by": "CONVERSION",
                        "palette": ["hsl(240,100%,90%)", "hsl(120,100%,50%)"]
                    }
                },
                {   
                    "name": "x",
                    "properties": {
                        "by": "CONVERSION"
                    }
                }
            ]
        },
        {
            "id": 7,
            "anchortext": "conversion_speed",
            "description": "vertical distribution of performance, with #1 country highlighted",
            "displaytext": "Converted sessions were, on average, 27% faster than non-converted sessions",
            "dimensions": [
                {   
                    "name": "color",
                    "properties": {
                        "by": "CONVERSION",
                        "palette": ["hsl(240,100%,90%)", "hsl(120,100%,50%)"]
                    }
                },
                {
                    "name": "x",
                    "properties": {
                        "by": "PAGELOADTIME"
                    }
                }
            ]
        },
        {
            "id": 8,
            "anchortext": "conversion_sessionlength",
            "description": "vertical distribution of performance, with #1 country highlighted",
            "displaytext": "Converted sessions were 9 pages long on average, compared with 3 pages for non-converted sessions",
            "dimensions": [
                {   
                    "name": "color",
                    "properties": {
                        "by": "CONVERSION",
                        "palette": ["hsl(240,100%,90%)", "hsl(120,100%,50%)"]
                    }
                },
                {
                    "name": "size",
                    "properties": {
                        "by": "SESSIONLENGTH"
                    }
                }
            ]
        }
    ]
}

=== atomless/akdv-rnd/mpulse-dswb-widgets/src/data/datajots/gapminder/stages.json
{
    "name": "",
    "description": "",
    "theme": "default",
    "data_format": "tsv",
    "stages": [
        {
            "id": 1,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "This cluster represents all 195 countries",
            "dimensions": []
        },
        {
            "id": 2,
            "anchortext": "devicetypes",
            "description": "cluster all forms by type",
            "displaytext": "Scaling by population shows the impact of India and China's proportion of world population.",
            "dimensions": [
                {
                    "name": "radius",
                    "properties": {
                        "by": "population"
                    }
                }
            ]
        },
        {
            "id": 2,
            "anchortext": "devicetypes",
            "description": "cluster all forms by type",
            "displaytext": "Coloring by life expectancy shows a lot of variation between countries",
            "dimensions": [
                {
                    "name": "radius",
                    "properties": {
                        "by": "population"
                    }
                },
                {
                    "name": "color",
                    "properties" : {
                        "by": "life_expectancy",
                        "palette": ["hsl(0,100%,50%)", "hsl(100,100%,70%)"]
                    }
                }
            ]
        },
        {
            "id": 2,
            "anchortext": "devicetypes",
            "description": "cluster all forms by type",
            "displaytext": "Grouping into Europe, Asia, Americas &amp; Africa<br> shows the life expectancy divide",
            "dimensions": [
                {
                    "name": "radius",
                    "properties": {
                        "by": "population"
                    }
                },
                {
                    "name": "color",
                    "properties" : {
                        "by": "life_expectancy",
                        "palette": ["hsl(0,100%,50%)", "hsl(100,100%,70%)"]
                    }
                },
                {
                    "name": "y",
                    "properties" : {
                        "by": "geo4",
                        "label": "Geo"
                    }
                }
            ]
        },
        {
            "id": 2,
            "anchortext": "devicetypes",
            "description": "cluster all forms by type",
            "displaytext": "Adding average income to the equation shows the divide between countries<br>The outlier in Asia is Qatar, with an average income of $130,000",
            "dimensions": [
                {
                    "name": "radius",
                    "properties": {
                        "by": "population"
                    }
                },
                {
                    "name": "color",
                    "properties" : {
                        "by": "life_expectancy",
                        "palette": ["hsl(0,100%,50%)", "hsl(100,100%,70%)"]
                    }
                },
                {
                    "name": "x",
                    "properties" : {
                        "by": "income",
                        "label": "Income"
                    }
                },
                {
                    "name": "y",
                    "properties" : {
                        "by": "geo4",
                        "label": "Geo"
                    }
                }
            ]
        }
    ]
}

=== atomless/akdv-rnd/mpulse-dswb-widgets/src/data/datajots/titanic/stages.json
{
    "name": "Titanic",
    "description": "Titanic",
    "theme": "default",
    "data_format": "tsv",
    "stages": [
        {
            "id": 1,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "Each point in this cluster represents a passenger aboard the titanic.",
            "dimensions": []
        },
        {
            "id": 3,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "60% of the passengers were male",
            "dimensions": [
                {
                    "name": "x",
                    "properties": {
                        "by": "sex"
                    }
                },
                {
                    "name": "color",
                    "properties": {
                        "by": "sex",
                        "palette": ["red","blue"]
                    }
                }
            ]
        },{
            "id": 4,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "Male passengers were generally older than the female passengers.<br/>We don't have the age for 20% of passengers (the cluster on the left)",
            "dimensions": [
                {
                    "name": "x",
                    "properties": {
                        "by": "age"
                    }
                },
                {
                    "name": "y",
                    "properties": {
                        "by": "sex"
                    }
                },
                {
                    "name": "color",
                    "properties": {
                        "by": "sex",
                        "palette": ["red","blue"]
                    }
                }
            ]
        },{
            "id": 5,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "Women were twice as likely to survive as men",
            "dimensions": [
                {
                    "name": "y",
                    "properties": {
                        "by": "sex"
                    }
                },
                {
                    "name": "color",
                    "properties": {
                        "by": "survived",
                        "palette": ["black","green"]
                    }
                }
            ]
        },{
            "id": 6,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "The majority of deaths were in third class.<br/>Almost 100% of women in first class survived",
            "dimensions": [
                {
                    "name": "y",
                    "properties": {
                        "by": "sex"
                    }
                },
                {
                    "name": "x",
                    "properties": {
                        "by": "pclass"
                    }
                },
                {
                    "name": "color",
                    "properties": {
                        "by": "survived",
                        "palette": ["black","green"]
                    }
                }
            ]
        },{
            "id": 7,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "The higher the fare, the less likely you were to die",
            "dimensions": [
                {
                    "name": "x",
                    "properties": {
                        "by": "fare"
                    }
                },
                {
                    "name": "color",
                    "properties": {
                        "by": "survived",
                        "palette": ["black","green"]
                    }
                }
            ]
        },{
            "id": 8,
            "anchortext": "start",
            "description": "shows all available data in a cloud",
            "displaytext": "Of course, more women survived than men",
            "dimensions": [
                {
                    "name": "x",
                    "properties": {
                        "by": "fare"
                    }
                },
                {
                    "name": "y",
                    "properties": {
                        "by": "sex"
                    }
                },
                {
                    "name": "color",
                    "properties": {
                        "by": "survived",
                        "palette": ["black","green"]
                    }
                }
            ]
        }
    ]
}
